### ISSUE TITLE
Notification not appearing when I swipe away the app from the recent list

### ISSUE THREAD

**Issue by ghost** [Red-Folder/bgs-core#49]
Hi,

I am developing a mobile application using cordova, android platform.
The mobile application will detect a beacon.
Currently, i installed https://github.com/katzer/cordova-plugin-local-notifications for the notification. 
However, when I swipe away the app from the recent list, I would no longer receive the notification.

I then research and most of the answers as to why the notification doesnt work when the app is close (take note: its not i force close the app from setting) is due to broadcast receiver.

I found this plugin and hence would like to ask if it could be a help to the problem I am facing. If yes, what do I need to configure or make changes so that it will help me on my problem?

Thank you.

**Comment by Red-Folder** [comment]
I'm afraid it's been sometime since I have used the plugin in development (purely because I've had no professional need or personal interest to do so) - as such I'm afraid I can't really provide much advise.

I believe what you are talking about is swiping the application - which I believe forces the app & its services to close.  If you have a read through some of the other issues in this repo, I believe others have had similar problems.  They have addresses this by amending the plugin so that it automatically restarts once it has been closed.  I'd advise you to have a look at that.

If you do find what you need, please update this issue (or even better the repo WIKI).

Thanks

**Comment by Red-Folder** [comment]
Closed - no response
