### ISSUE TITLE
Error: Failed to fetch plugin https://github.com/Red-Folder/bgs-sample.git

### ISSUE THREAD

**Issue by GamalSebaee** [Red-Folder/bgs-core#64]
cordova plugin add https://github.com/Red-Folder/bgs-sample.git
this is 
Error: Failed to fetch plugin https://github.com/Red-Folder/bgs-sample.git via g
it.
Either there is a connection problems, or plugin spec is incorrect:
        Error: "git" command line tool is not installed: make sure it is accessi
ble on your PATH.
how i can solve this problem

**Comment by Red-Folder** [comment]
Based on the error you are having a problem with git when the Cordova CLI is attempting to download the plugin.

"git" is a command line tool for working with Git source repositories.  In this case the git tool is being asked by Cordova to download the bgs-sample plugin.  Your operating system however cannot find the git command.

This will either be because you have not installed a git command line tool or the operating system cannot find it (the directory is not in the path).

if you haven''t done already, search Google for the below for your operating system:

> "git" command line tool is not installed: make sure it is accessi
ble on your PATH.

I will close this issue as your problem is with the Cordova/ Git tooling - not the plugin

**Comment by DhruvGupta5** [comment]
refer to: (RESOLVED)
https://github.com/Red-Folder/bgs-core/issues/86
