### ISSUE TITLE
Keep service and change page

### ISSUE THREAD

**Issue by chlamy** [Red-Folder/bgs-core#66]
Hello,

I use this plugin on my app, it works when I call start function but when I change page the service is canceled.

I have this

```
function start() {
    service.getStatus(function(r){startService(r);}, function(e){handleError(e);});
}

function startService(data) {
   if (data.ServiceRunning) {
      enableTimer(data);
   } 
   else {
        service.startService(function(r){enableTimer(r);}, function(e){handleError(e);});
   }
}

function enableTimer(data) {
   if(data.TimerEnabled) {
        allDone();
   } 
   else {
        service.enableTimer(1, function(r){allDone(r);}, function(e){handleError(e);});
   }
}

function allDone() {
    setInterval(function(){showNotif();},5000);
}
```

Thanks.

**Comment by Red-Folder** [comment]
How do you know that the background service has been cancelled?

Note that nothing in JavaScript would continue to work between page changes (because the entire JavaScript environment is recreated).  So the background service maybe working - you just can't see if because you are looking at JavaScript to monitor it

**Comment by Red-Folder** [comment]
Closing ... no response
