### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by anup5708** [Red-Folder/bgs-core#75]
Hi,

I look around your sample example of background service, which seems good to have a change of text for every 60sec.

But when the app goes background is it the background service is still running.because when i open the app it again starts an alert messages as "Service now running" in allDone() method.

What to do If I need to pop up a simple "hello" message for every 5 seconds even the app is open and app is closed. please help...

**Comment by Red-Folder** [comment]
You'd need to use an Android notification (https://developer.android.com/guide/topics/ui/notifiers/notifications.html)

Within the Service code, fire off a notification at the relevant point (this will require Java code).

If the app is closed, you are unable to provide a JavaScript alert or similar (because there is no JavaScript context to run in).
